export { analyzeProject } from './analyze.js';
export type { Analysis, AnalysisNote, Boundary, Env, ModuleReport, ServerOnlyViolation } from './analyze.js';
export { parseModule } from './parse.js';
export type { ParsedModule, ImportEntry, ReexportEntry, Directive } from './parse.js';
export { readBuildInfo, parseManifestText } from './buildinfo.js';
export type { PropFinding, PropsCrossing, PropVerdict } from './props.js';
export type { BuildInfo, ModuleCost, ChunkCost, ManifestModule } from './buildinfo.js';
export { renderReport, renderExplanation, renderExplanationList, formatBytes } from './report.js';
export { strictGate } from './gate.js';
export type { GateResult } from './gate.js';
export { EXPLANATIONS, findExplanation } from './explain.js';
export type { Explanation } from './explain.js';
export { renderHtml } from './html.js';
